# -*- coding: utf-8 -*-
from . import res_partner
from . import sale_order
from . import product_template
from . import product_product
from . import sale_order_line
from . import account_move
from . import account_move_line
from . import account_payment
from . import res_users
from . import account_bank_statement_line
from . import product_supplierinfo
from . import stock_warehouse_orderpoint
from . import mrp_bom
from . import mrp_production
from . import purchase_order
from . import stock_picking
from . import stock_scrap
from . import stock_move_line
from . import purchase_order_ecm_reporting
from . import ecm_sales_order_by_line_reporting
from . import stock_move
from . import  catlog_section